sudo: required
services:
  - docker

before_install:
  - docker build -t rranga99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rranga99/react-test npm test

after_success:
  - docker build -t rranga99/multi-client ./client
  - docker build -t rranga99/multi-nginx ./nginx
  - docker build -t rranga99/multi-server ./server
  - docker build -t rranga99/multi-worker ./worker
  #login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push rranga99/multi-client
  - docker push rranga99/multi-nginx
  - docker push rranga99/multi-server
  - docker push rranga99/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-396613015605"
  bucker_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


